version: "3.4"

services:
  scs-redis:
    image: redis:latest
    restart: always
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./etc/localtime:/etc/localtime:ro

  scs-schedule:
    build: ./image/scs-df
    links:
      - scs-redis
    restart: always
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./etc/localtime:/etc/localtime:ro
      - ../src:/data/scs:rw
      - ../logs:/data/logs:rw
    entrypoint: ["/data/run_schedule.sh"]
    environment:
      - FLASK_APP=/data/scs/autoapp.py
      - PYTHONUNBUFFERED=0

  scs-backscript:
    build: ./image/scs-df
    links:
      - scs-redis
    restart: always
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./etc/localtime:/etc/localtime:ro
      - ../src:/data/scs:rw
      - ../logs:/data/logs:rw
    entrypoint: ["/data/run_celery.sh"]
    environment:
      - FLASK_APP=/data/scs/autoapp.py
      - PYTHONUNBUFFERED=0

  scs-api:
    build: ./image/scs-df
    links:
      - scs-redis
    # ports:
    # - "${SCS_PORT_API}:5999"
    restart: always
    entrypoint: ["/data/run_gunicorn.sh"]
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./etc/localtime:/etc/localtime:ro
      - ../src:/data/scs:rw
      - ../logs:/data/logs:rw
    environment:
      - FLASK_APP=/data/scs/autoapp.py
      - PYTHONUNBUFFERED=0

  # web 入口
  scs-ng:
    image: nginx:latest
    ports:
      - "${SCS_PORT_FRONT}:80"
      - "${SCS_PORT_API}:8099"
    restart: always
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./etc/localtime:/etc/localtime:ro

      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro

      - ../logs/nginx:/var/log/nginx:rw
      - ../web-frontend:/data/www/web-frontend:ro

    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
